turismo_real/AppIntranet/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url
from AppIntranet.views import CreateDepartamentoView, EditDepaView, ListDepartamentoView
from AppIntranet.views import CreateServicioExtraView, EditServicioExtraView, ListServicioExtraView
from AppIntranet.views import listado_tours,servicios,otros_servicios,CreateServicioExtraView,EditServicioExtraView
from AppIntranet.views import CreateInventarioView, EditInventarioView, ListInventarioView
from AppIntranet.views import CreateUsuarioView, EditUsuarioView, ListUsuarioView
from AppIntranet.views import CreateDetalleInventarioView, EditDetalleInventarioView, ListDetalleInventarioView
from AppIntranet.views import CreateTipoEstado, TipoEstadoEditView, ListTipoEstadoView
from AppIntranet.views import CreateImagenDepartamentoView, EditImagenDepartamentoView, ListImagenDepartamentoView
from AppIntranet.views import CreateMantencionView, EditMantencionView, ListMantencionView
from AppIntranet.views import LoginAdmView, LogoutView

from AppIntranet.views import ReporteView, AgendaView, MantenedoresView, CheckinView
from AppIntranet.views import asignaciones_transporte,asignacion_conductor,asignacion_vehiculo
from AppIntranet.views import CheckOutView

urlpatterns = [
    
    path('index',views.index, name = "intranet"),

    url(r'^agenda$', AgendaView.as_view(), name='agenda'),
    url(r'^checkin$', CheckinView.as_view(), name='checkin'),
    url(r'^checkout$', CheckOutView.as_view(), name='check_out'),
    url(r'^mantenedores$', MantenedoresView.as_view(), name='mantenedores'),


    url(r'^reporte$', ReporteView.as_view(), name='reporte'),
    url(r'^estado/all$', ListTipoEstadoView.as_view(), name='list_estados'),
    url(r'^estado/new_estado$', CreateTipoEstado.as_view(), name='create_estado'),

    
    url(r'^departamento/add$', CreateDepartamentoView.as_view(), name='create_depa'),
    url(r'^departamento/edit/(?P<pk>[0-9]+)$', EditDepaView.as_view(), name='edit_depa'),
    url(r'^departamento/all$', ListDepartamentoView.as_view(), name='list_depa'),

    url(r'^otros_servicios/add$', CreateServicioExtraView.as_view(), name='create_serv'),
    url(r'^otros_servicios/edit/(?P<pk>[0-9]+)$', EditServicioExtraView.as_view(), name='edit_serv'),
    url(r'^otros_servicios/all$', ListServicioExtraView.as_view(), name='list_serv'),

    
    path('servicios/', views.servicios, name='list_serv_all'),
    path('otros_servicios/', views.otros_servicios, name='list_otros_serv'),

    path('aniadir_tour/', views.añadir_tour, name='add_tour'),
    path('editar_tour/', views.editar_tour, name='edit_tour'),
    path('tours_disponibles/', views.listado_tours, name='list_tours'),
    path('mantenedor_transporte/', views.transporte, name='list_transporte'),
    path('asignaciones_transporte/', views.asignaciones_transporte, name='asig_transporte'),
    path('asignacion_conductor/', views.asignacion_conductor, name='asig_conductor'),
    path('asignacion_vehiculo/', views.asignacion_vehiculo, name='asig_vehiculo'),

    url(r'^servicio/add$', CreateServicioExtraView.as_view(), name='create_serv'),
    url(r'^servicio/edit/(?P<pk>[0-9]+)$', EditServicioExtraView.as_view(), name='edit_serv'),
    url(r'^servicio/all$', ListServicioExtraView.as_view(), name='list_serv'),

    url(r'^inventario/add$', CreateInventarioView.as_view(), name='create_inv'),
    url(r'^inventario/edit/(?P<pk>[0-9]+)$', EditInventarioView.as_view(), name='edit_inv'),
    url(r'^inventario/all/(?P<pk>[0-9]+)$', ListInventarioView.as_view(), name='list_inv'),

    url(r'^usuario/add$', CreateUsuarioView.as_view(), name='create_usr'),
    url(r'^usuario/edit/(?P<pk>[0-9]+)$', EditUsuarioView.as_view(), name='edit_usr'),
    url(r'^usuario/all$', ListUsuarioView.as_view(), name='list_usr'),

    
    url(r'^tipoestado/add$', CreateTipoEstado.as_view(), name='create_tipoestado'),
    url(r'^tipoestado/edit/(?P<pk>[0-9]+)$', TipoEstadoEditView.as_view(), name='edit_tipoestado'),
    url(r'^tipoestado/all$', ListTipoEstadoView.as_view(), name='list_tipoestado'),

    url(r'^detalle/add$', CreateDetalleInventarioView.as_view(), name='create_deta'),
    url(r'^detalle/edit/(?P<pk>[0-9]+)$', EditDetalleInventarioView.as_view(), name='edit_deta'),
    url(r'^detalle/all/(?P<pk>[0-9]+)$', ListDetalleInventarioView.as_view(), name='list_deta'),

    url(r'^imagen/add$', CreateImagenDepartamentoView.as_view(), name='create_img'),
    url(r'^imagen/edit/(?P<pk>[0-9]+)$', EditImagenDepartamentoView.as_view(), name='edit_img'),
    url(r'^imagen/all/(?P<pk>[0-9]+)$', ListImagenDepartamentoView.as_view(), name='list_img'),

    url(r'^mantencion/add$', CreateMantencionView.as_view(), name='create_mant'),
    url(r'^mantencion/edit/(?P<pk>[0-9]+)$', EditMantencionView.as_view(), name='edit_mant'),
    url(r'^mantencion/all/(?P<pk>[0-9]+)$', ListMantencionView.as_view(), name='list_mant'),

    path('', LoginAdmView.as_view(), name='intranet_login'), 
    url(r'^logout$', LogoutView.as_view(), name='intranet_logout'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


turismo_real/AppWeb/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url

from AppWeb.views import Create as CreateUser, LoginView, LogoutView, ActivacionView #Usuario
from AppWeb.views import ListDepartamentosView, DetailDepartamentoView, SearchDepaView #Departamento
from AppWeb.views import ReservaView, CreateReservaView, MisReservasView #pruebas
from AppWeb.views import ListOcupanteView, CreateOcupanteView, EditOcupanteView, DeleteOcupanteView #Ocupantes
from AppWeb.views import TransporteView #Transporte
from AppWeb.views import PagoExitosoView, PagoErrorView #Pago
from AppWeb.views import ServicioAddView


urlpatterns = [
    
    path('',views.index, name = "index"),
    
    #region Ocupante
    url(r'^ocupantes/(?P<pk>[0-9]+)$', ListOcupanteView.as_view(), name='ocupantes'), 
    url(r'^ocupantes/add$', CreateOcupanteView.as_view(), name='create_ocu'), 
    url(r'^ocupantes/edit/(?P<pk>[0-9]+)$', EditOcupanteView.as_view(), name='edit_ocu'), 
    url(r'^ocupantes/del/(?P<pk>[0-9]+)$', DeleteOcupanteView.as_view(), name='del_ocu'), 
    #endregion Ocupante

    #region reserva
    url(r'^reserva$', ReservaView.as_view(), name='reserva'), 
    url(r'^mis_reservas$', MisReservasView.as_view(), name='mis_reservas'), 
    url(r'^reserva/add/(?P<pk>[0-9]+)$', CreateReservaView.as_view(), name='reserva_depto'), 
    url(r'^reserva/servicio/(?P<pk>[0-9]+)$', ServicioAddView.as_view(), name='cont_serv'), 
    #end reserva

    #region Departamento
    url(r'^departamentos$', ListDepartamentosView.as_view(), name='deptos_list'), #Cargar departamentos
    url(r'^busca/departamento$', SearchDepaView.as_view(), name='busca_depto'), #Cargar departamentos
    url(r'^departamento/(?P<pk>[0-9]+)$', DetailDepartamentoView.as_view(), name='detail_depto'), #Detalle del departamento(ID)

    #endregion Departamento
    
    #region usuario
    url(r'^new_user$', CreateUser.as_view(), name='create_user'), #Registrarse
    url(r'^login$', LoginView.as_view(), name='users_login'), #Iniciar sesion
    url(r'^logout$', LogoutView.as_view(), name='users_logout'), #Cerrar sesion
    url(r'^activation/(?P<pk>[0-9]+)$', ActivacionView.as_view(), name='activation'), #Activar usuario
    #endregion usuario

    #Region transporte
    url(r'^Transporte$', TransporteView.as_view(), name='Transporte'), #Muestra el transporte
    #endregion transporte

    #region Pagp
    url(r'^pago/exitoso$', PagoExitosoView.as_view(), name='PagoExito'),
    url(r'^pago/error$', PagoErrorView.as_view(), name='PagoError'),
    #endregion
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

turismo_real/turismo_real/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('AppWeb.urls')),
    path('intranet/',include('AppIntranet.urls')),
    url(r'^khipu/', include('khipu.urls')),

] 

turismo_real/AccesoDatos/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
#Blank false = required

# region Mantencion

class TipoUsuario(models.Model):
    nombre = models.CharField(max_length=50,blank=False)
    descripcion = models.CharField(max_length=500,blank=True)
    
    def __str__(self):
        return self.nombre


class Usuario(AbstractUser):
    fk_tipo_usuario = models.ForeignKey(TipoUsuario,null=True,blank=True,on_delete=models.CASCADE)

    rut = models.CharField(max_length=11,blank=False)
    #fecha_nac = models.DateField( blank=False)
    direccion = models.CharField(max_length=50,blank=False)
    telefono = models.CharField(max_length=12,blank=False)

    def _str_(self):
        return self.username

class ServicioExtra(models.Model):
    nombre = models.CharField(max_length=50,blank=False)
    descripcion = models.CharField(max_length=500,blank=False)
    costoDiario = models.IntegerField(blank=False)
    imagen = models.FileField(upload_to='documents/', blank=True)
    
    def __str__(self):
        return self.nombre

class Region(models.Model):
    nombre = models.CharField(max_length=50,blank=False)
    
    def __str__(self):
        return self.nombre

class Comuna(models.Model):
    fk_region = models.ForeignKey(Region,null=False,blank=False,on_delete=models.CASCADE)
    
    nombre = models.CharField(max_length=50,blank=False)
    
    def __str__(self):
        return self.nombre


class Departamento(models.Model):
    fk_comuna = models.ForeignKey(Comuna,null=True,blank=True,on_delete=models.CASCADE)
    
    direccion = models.CharField(max_length=50,blank=False)
    metros = models.IntegerField(blank=False)
    cantPersonas = models.IntegerField(blank=False)
    cantBanios = models.IntegerField(blank=False)
    cantDormitorios = models.IntegerField(blank=False)
    descripcion = models.CharField(max_length=500, blank=False)
    precioNoche = models.IntegerField(blank=False)

    estado = models.BooleanField(blank=True)
    dividendo = models.IntegerField(blank=False)
    contribuciones = models.IntegerField(blank=False)

    imagen = models.FileField(upload_to='documents/',blank=False)
    
    def __str__(self):
        return self.direccion

class Inventario(models.Model):
    fk_empleador = models.ForeignKey(Usuario,null=True,blank=True,on_delete=models.CASCADE)
    fk_departamento = models.ForeignKey(Departamento,null=False,blank=False,on_delete=models.CASCADE)

    nombre = models.CharField(max_length=50,blank=False)
    descripcion = models.CharField(max_length=500,blank=False)
    fechaRegistro = models.DateField( blank=False)
    
    def __str__(self):
        return self.nombre

class DetalleInventario(models.Model):
    fk_inventario = models.ForeignKey(Inventario,null=False,blank=False,on_delete=models.CASCADE)

    nombreObjeto = models.CharField(max_length=50,blank=False)
    cantidad = models.IntegerField(blank=False)
    descripcion = models.CharField(max_length=500,blank=True)
    costo = models.IntegerField(blank=False)
    
    def __str__(self):
        return self.nombreObjeto

class ImagenDepartamento(models.Model):
    fk_departamento = models.ForeignKey(Departamento,null=False,blank=False,on_delete=models.CASCADE)

    imagen = models.FileField(upload_to='documents/', blank=False)
    descripcion = models.CharField(max_length=500, blank=False)
    
    def __str__(self):
        return self.descripcion

class Mantencion(models.Model):
    fk_departamento = models.ForeignKey(Departamento,null=True,blank=True,on_delete=models.CASCADE)
    fk_empleado = models.ForeignKey(Usuario,null=True,blank=True,on_delete=models.CASCADE)

    nombre = models.CharField(max_length=50,blank=False)
    descripcion = models.CharField(max_length=500,blank=False)
    costo = models.IntegerField(blank=False)
    fechaRegistro = models.DateField( blank=True)
    fechaInicioProg = models.DateField( blank=False)
    fechaTerminoProg = models.DateField( blank=False)
    fechaRealInicio = models.DateField( blank=True, null=True)
    fechaRealTermino = models.DateField( blank=True, null=True)
    
    def __str__(self):
        return self.nombre

# endregion

# region Arriendo

class TipoEstado(models.Model):
    nombre = models.CharField(max_length=50,blank=False)
    descripcion = models.CharField(max_length=500,blank=True)
    
    def __str__(self):
        return self.nombre

class Arriendo(models.Model):
    fk_usuario = models.ForeignKey(Usuario,null=False,blank=False,on_delete=models.CASCADE)
    fk_tipo_estado = models.ForeignKey(TipoEstado,null=False,blank=False,on_delete=models.CASCADE)

    fechaRegistro = models.DateField( blank=False) 
    totalArriendo = models.IntegerField(blank=False)
    totalMulta = models.IntegerField(blank=True)
    totalServicio = models.IntegerField(blank=True)

    cantDias = models.IntegerField(blank=True)
    cantNinos = models.IntegerField(blank=True)
    cantAdultos = models.IntegerField(blank=True)

    cantPersonas = models.IntegerField()

    def __str__(self):
        return self.totalArriendo

class Reserva(models.Model):

    fechaInicio = models.DateField( blank=True) 
    fechaTermino = models.DateField( blank=True)
    costo = models.IntegerField()

    def __str__(self):
        return self.costo

class CheckIn(models.Model):
    fk_usuario = models.ForeignKey(Usuario,null=True,blank=True,on_delete=models.CASCADE)

    fechaRegistro = models.DateField( blank=True) 
    abonoFinal = models.IntegerField()
    observacion = models.CharField(max_length=500,blank=True)
    
    def __str__(self):
        return self.abonoFinal

class DetalleCheckIn(models.Model):
    fk_check_in = models.ForeignKey(CheckIn,null=True,blank=True,on_delete=models.CASCADE)

    nombreObjeto = models.CharField(max_length=500,blank=True)
    cantRegistrada = models.IntegerField()
    observacion = models.CharField(max_length=500,blank=True)
    
    def __str__(self):
        return self.nombreObjeto

class CheckOut(models.Model):
    fk_usuario = models.ForeignKey(Usuario,null=True,blank=True,on_delete=models.CASCADE)

    fechaRegistro = models.DateField( blank=True) 
    costoMulta = models.IntegerField()
    observacion = models.CharField(max_length=500,blank=True)

    def __str__(self):
        return self.costoMulta

class DetalleCheckOut(models.Model):
    fk_check_out = models.ForeignKey(CheckOut,null=True,blank=True,on_delete=models.CASCADE)

    nombreObjeto = models.CharField(max_length=500,blank=True)
    cantRegistrada = models.IntegerField()
    observacion = models.CharField(max_length=500,blank=True)
    
    def __str__(self):
        return self.nombreObjeto

class Multa(models.Model):
    fk_check_out = models.ForeignKey(CheckOut,null=True,blank=True,on_delete=models.CASCADE)

    nombreObjeto = models.CharField(max_length=500,blank=True)
    cantFaltante = models.IntegerField()
    observacion = models.CharField(max_length=500,blank=True)
    
    def __str__(self):
        return self.nombreObjeto

class Ocupante(models.Model):
    fk_arriendo = models.ForeignKey(Arriendo,null=True,blank=True,on_delete=models.CASCADE)
    
    rut = models.CharField(max_length=11,blank=False)
    nombres = models.CharField(max_length=50,blank=False)
    apellidos = models.CharField(max_length=50,blank=False)
    edad = models.IntegerField(blank=False)

    def __str__(self):
        return self.rut

class DetalleArriendo(models.Model):
    fk_departamento = models.ForeignKey(Departamento,null=True,blank=True,on_delete=models.CASCADE)
    fk_servicio_extra = models.ForeignKey(ServicioExtra,null=True,blank=True,on_delete=models.CASCADE)
    fk_arriendo = models.ForeignKey(Arriendo,null=True,blank=True,on_delete=models.CASCADE)
    fk_reserva = models.ForeignKey(Reserva,null=True,blank=True,on_delete=models.CASCADE)
    fk_check_in = models.ForeignKey(CheckIn,null=True,blank=True,on_delete=models.CASCADE)
    fk_check_out = models.ForeignKey(CheckOut,null=True,blank=True,on_delete=models.CASCADE)

    

    def __str__(self):
        return self.fk_arriendo

# endregion

turismo_real/AppIntranet/models.py
from django.db import models

# Create your models here.

turismo_real/AppIntranet/templates/AppIntranet/usuario/usuario.html
<script type="text/javascript">
  $(document).ready(function () {

    $("#btn_add").on("click", function (e) {
      if (validarFormulario()) {
        e.preventDefault();
        $.ajax({
          type: "POST",
          url: "/intranet/usuario/add",
          data: $('#form_add').serialize(),
          success: function (data) {
            if (data.type == 'error') {
              swal({
                title: data.tittle,
                text: data.mensaje,
                type: data.type,
                confirmButtonText: 'Aceptar'
              })
            } else {
              swal({
                title: data.tittle,
                text: data.mensaje,
                type: data.type,
                confirmButtonText: 'Aceptar'
              }, function (result) {
                window.location.href = '/intranet/usuario/all';
              });
            }
          },
          error: function (data) {
            swal({
              title: data.tittle,
              text: data.mensaje,
              type: data.type,
              confirmButtonText: 'Aceptar'
            })
          }
        });
      }
    })
    //Fin Add Usuario

    //Edit Usuario
    $("#btn_edit").on("click", function (e) {
      if (validarFormulario()) {
        e.preventDefault();
        $.ajax({
          type: "POST",
          url: "/intranet/usuario/edit/" + '{{pk}}',
          data: $('#form_edit').serialize(),
          success: function (data) {
            if (data.type == 'error') {
              swal({
                title: data.tittle,
                text: data.mensaje,
                type: data.type,
                confirmButtonText: 'Aceptar'
              })
            } else {
              swal({
                title: data.tittle,
                text: data.mensaje,
                type: data.type,
                confirmButtonText: 'Aceptar'
              }, function (result) {
                window.location.href = '/intranet/usuario/all';
              });
            }
          },
          error: function (data) {
            swal({
              title: data.tittle,
              text: data.mensaje,
              type: data.type,
              confirmButtonText: 'Aceptar'
            })
          }
        });
      }
    })

    $('#id_rut').on('paste', function (e) {
      e.preventDefault();
    });
    $('#id_rut').on('change', function (e) {
      var rut = e.target.value;
      formatRUT(e);
      validateRUT(rut);
      validarFormulario();
    });

    $('#id_username').on('paste', function (e) {
      e.preventDefault();
    });

    $('#id_username').on('change', function (e) {
      var username = e.target.value;
      validateUsername(rut);
      validarFormulario();
    });

    $('#id_email').on('paste', function (e) {
      e.preventDefault();
    });

    $('#id_email').on('change', function (e) {
      var email = e.target.value;
      validateEmail(email);
      validarFormulario();
    });

    $('#id_first_name').on('paste', function (e) {
      e.preventDefault();
    });

    $('#id_first_name').on('change', function (e) {
      var nombre = e.target.value;
      validateNombre(nombre);
      validarFormulario();
    });

    $('#id_last_name').on('paste', function (e) {
      e.preventDefault();
    });

    $('#id_last_name').on('change', function (e) {
      var apellido = e.target.value;
      validateApellido(apellido);
      validarFormulario();
    });

    $('#id_direccion').on('paste', function (e) {
      e.preventDefault();
    });

    $('#id_direccion').on('change', function (e) {
      var direccion = e.target.value;
      validateDireccion(direccion);
      validarFormulario();
    });

    $('#id_telefono').on('paste', function (e) {
      e.preventDefault();
    });

    $('#id_telefono').on('change', function (e) {
      var direccion = e.target.value;
      validateDireccion(direccion);
      validarFormulario();
    });

    function validarFormulario() {
      var username = $('#id_username').val();
      if (validateUsername(username)) {
        var nombres = $('#id_first_name').val();
        if (validateNombre(nombres)) {
          var ap = $('#id_last_name').val();
          if (validateApellido(ap)) {
            var rut = $('#id_rut').val();
            if (validateRUT(rut)) {
              var email = $('#id_email').val();
              if (validateEmail(email)) {
                var direccion = $('#id_direccion').val();
                if (validateDireccion(direccion)) {
                  var telefono = $('#id_telefono').val();
                  if (validateTelefono(telefono)) {
                    var pass = $('#id_password').val();
                    if (validatePassword(pass)) {
                      return true;
                    }
                  }
                }
              }
            }
          }
        }
      }

      return false;
    }

    ///Funcion para validar que el input rut no este vacio, y sea valido
    function validateRUT(rut) {
      const new_rut = rut.replace(/\./g, '').replace(/\-/g, '').replace(/\ /g, '').trim()
      const len = new_rut.length
      const number = new_rut.substring(0, len - 1)
      const digit = new_rut.substring(len - 1, len)
      let valid_digit = false
      let valid_number = false
      if (digit.match(/^-{0,1}\d+$/) || digit.toLowerCase() === 'k') {
        valid_digit = true
      }
      if (number.match(/^-{0,1}\d+$/) && number.length >= 5) {
        valid_number = true
      }
      const upperDigit = digit.toUpperCase();

      let valid_modulo11 = false
      const serie_n = [2, 3, 4, 5, 6, 7]
      let sum = 0
      for (let j = 0; j < number.length; j++) {
        sum += parseInt(number.substring(number.length - j - 1, number.length - j)) * serie_n[j % (serie_n.length)]
      }
      const rest = (11 - (sum % 11)) % 11
      const verif = (rest === 10) ? "K" : rest.toString()
      if (verif === upperDigit) {
        valid_modulo11 = true
      }

      if (rut == "") {
        $('#id_rut')[0].setCustomValidity("Debe ingresar un rut.")
        return false
      } else {
        if (!(valid_digit && valid_number && valid_modulo11)) {
          $('#id_rut')[0].setCustomValidity("Debe ingresar un rut valido.")
          return false
        }
        else {
          $('#id_rut')[0].setCustomValidity("")
          return true
        }
      }

    }

    ///Funcion para darle el formato de run al input rut
    function formatRUT(e) {
      const rut = e.target.value.replace(/\./g, '').replace(/\-/g, '').replace(/\ /g, '')
      const len = rut.length
      if (len > 0) {
        let digit = "-" + rut.substring(len - 1)
        for (let i = len - 1; i > 0; i -= 3) {
          digit = (i > 3) ? '.' + rut.substring(i - 3, i) + digit : rut.substring(i - 3, i) + digit
        }
        $('#' + e.target.id).val(digit.toUpperCase())
      }
    }

    ///Funcion para validar que el input username no este vacio
    function validateUsername(username) {

      if (username.length === 0) {
        $('#id_username')[0].setCustomValidity("Debe ingresar Nombre usuario.")
        return false
      }
      else {
        $('#id_username')[0].setCustomValidity("")

        return true
      }
    }

    ///Funcion para validar que el input email no este vacio y tenga la estructura valida
    function validateEmail(email) {
      if (email.length === 0) {
        $('#id_email')[0].setCustomValidity("Debe ingresar Correo Electronico.")
        return false
      }
      else {
        if (!(/^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/.test(email))) {
          $('#id_email')[0].setCustomValidity("Debe ingresar un Correo electronico valido.")
          return false
        }
        else {
          $('#id_email')[0].setCustomValidity("")
          return true
        }
      }
    }

    ///Funcion para validar que el input first_name no este vacio
    function validateNombre(nombre) {

      if (nombre.length === 0) {
        $('#id_first_name')[0].setCustomValidity("Debe ingresar su Nombre.")
        return false
      }
      else {
        $('#id_first_name')[0].setCustomValidity("")

        return true
      }
    }

    ///Funcion para validar que el input last_name no este vacio
    function validateApellido(ap) {

      if (ap.length === 0) {
        $('#id_last_name')[0].setCustomValidity("Debe ingresar su Apellido.")
        return false
      }
      else {
        $('#id_last_name')[0].setCustomValidity("")
        return true
      }
    }

    ///Funcion para validar que el input direccion no este vacio
    function validateDireccion(direccion) {

      if (direccion.length === 0) {
        $('#id_direccion')[0].setCustomValidity("Debe ingresar su Dirección.")
        return false
      }
      else {
        $('#id_direccion')[0].setCustomValidity("")
        return true
      }
    }

    ///Funcion para validar que el input telefono no este vacio
    function validateTelefono(telefono) {

      if (telefono.length === 0) {
        $('#id_telefono')[0].setCustomValidity("Debe ingresar su número Telefónico.")
        return false
      }
      else {
        $('#id_telefono')[0].setCustomValidity("")
        return true
      }
    }

    /*Funcion para validar que el input password no este vacio y que cumpla con
    las caracteristicas de una Password segura:
    -Entre 8 a 15 caracteres
    -Una letra minúscula
    -Una letra mayúscula
    -Un dígito numérico
    -Un carácter especial
    */
    function validatePassword(pass) {
      var decimal = /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[^a-zA-Z0-9])(?!.*\s).{8,15}$/;
      if (pass.length === 0) {
        $('#id_password')[0].setCustomValidity("Debe ingresar una contraseña")
        return false
      } else {
        if (!(pass.match(decimal))) {
          $('#id_password')[0].setCustomValidity("Contraseña debe contener(Entre 8 a 15 caracteres, una letra minúscula, una letra mayúscula, un dígito numérico y un carácter especial).")
          return false
        }
        else {
          $('#id_password')[0].setCustomValidity("")
          return true
        }
      }

    }

  });


</script>