turismo_real/AppWeb/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url

from AppWeb.views import Create as CreateUser, LoginView, LogoutView, ActivacionView #Usuario
from AppWeb.views import ListDepartamentosView, DetailDepartamentoView, SearchDepaView #Departamento
from AppWeb.views import ReservaView, CreateReservaView, MisReservasView #pruebas
from AppWeb.views import ListOcupanteView, CreateOcupanteView, EditOcupanteView, DeleteOcupanteView #Ocupantes
from AppWeb.views import TransporteView #Transporte
from AppWeb.views import PagoExitosoView, PagoErrorView #Pago
from AppWeb.views import ServicioAddView


urlpatterns = [
    
    path('',views.index, name = "index"),
    
    #region Ocupante
    url(r'^ocupantes/(?P<pk>[0-9]+)$', ListOcupanteView.as_view(), name='ocupantes'), 
    url(r'^ocupantes/add$', CreateOcupanteView.as_view(), name='create_ocu'), 
    url(r'^ocupantes/edit/(?P<pk>[0-9]+)$', EditOcupanteView.as_view(), name='edit_ocu'), 
    url(r'^ocupantes/del/(?P<pk>[0-9]+)$', DeleteOcupanteView.as_view(), name='del_ocu'), 
    #endregion Ocupante

    #region reserva
    url(r'^reserva$', ReservaView.as_view(), name='reserva'), 
    url(r'^mis_reservas$', MisReservasView.as_view(), name='mis_reservas'), 
    url(r'^reserva/add/(?P<pk>[0-9]+)$', CreateReservaView.as_view(), name='reserva_depto'), 
    url(r'^reserva/servicio/(?P<pk>[0-9]+)$', ServicioAddView.as_view(), name='cont_serv'), 
    #end reserva

    #region Departamento
    url(r'^departamentos$', ListDepartamentosView.as_view(), name='deptos_list'), #Cargar departamentos
    url(r'^busca/departamento$', SearchDepaView.as_view(), name='busca_depto'), #Cargar departamentos
    url(r'^departamento/(?P<pk>[0-9]+)$', DetailDepartamentoView.as_view(), name='detail_depto'), #Detalle del departamento(ID)

    #endregion Departamento
    
    #region usuario
    url(r'^new_user$', CreateUser.as_view(), name='create_user'), #Registrarse
    url(r'^login$', LoginView.as_view(), name='users_login'), #Iniciar sesion
    url(r'^logout$', LogoutView.as_view(), name='users_logout'), #Cerrar sesion
    url(r'^activation/(?P<pk>[0-9]+)$', ActivacionView.as_view(), name='activation'), #Activar usuario
    #endregion usuario

    #Region transporte
    url(r'^Transporte$', TransporteView.as_view(), name='Transporte'), #Muestra el transporte
    #endregion transporte

    #region Pagp
    url(r'^pago/exitoso$', PagoExitosoView.as_view(), name='PagoExito'),
    url(r'^pago/error$', PagoErrorView.as_view(), name='PagoError'),
    #endregion
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

turismo_real/turismo_real/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('AppWeb.urls')),
    path('intranet/',include('AppIntranet.urls')),
    url(r'^khipu/', include('khipu.urls')),

] 

turismo_real/AppWeb/models.py
from django.db import models

# Create your models here.

turismo_real/AccesoDatos/forms.py
from django import forms
from AccesoDatos.models import *
from django.contrib.auth.forms import AuthenticationForm


# region usuario


class LoginForm(forms.Form):

    # Nombre usuario
    usr = forms.CharField(label='Nombre de usuario', max_length=20)
    usr.widget.attrs.update(
        {'class': 'form-control', 'placeholder': 'Nombre de usuario', 'required': 'required', 'minlength':'2',
            'max_length':'20'})

    # Contraseña
    pwd = forms.CharField(label='Contraseña',
                          widget=forms.PasswordInput(), max_length=20)
    pwd.widget.attrs.update(
        {'class': 'form-control', 'placeholder': 'Contraseña', 'required': 'required',})


class UsuarioForm(forms.ModelForm):

    class Meta:
        model = Usuario
        exclude = ['is_staff', 'is_superuser', 'last_login',
                   'date_joined', 'groups', 'user_permissions', 'is_active', 'fk_tipo_usuario']
        labels = {'username': 'Nombre de usuario', 'password': 'Contraseña',
                  'first_name': 'Nombre', 'last_name': 'Apellido', 'email': 'Correo',
                  'rut': 'Rut',  'direccion': 'Dirección',
                  'telefono': 'Teléfono'}

        help_texts = {'username': ' ', }

        widgets = {
            'email': forms.EmailInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Correo Electronico',
                    'required': 'required',
                }
            ),
            'first_name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese su nombre',
                    'required': 'required',
                }
            ),
            'username': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Nombre de usuario',
                    'required': 'required',
                }
            ),
            'last_name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese su apellido',
                    'required': 'required',
                }
            ),
            'password': forms.PasswordInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese su contraseña',
                    'required': 'required',
                }
            ),
            'rut': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese su Rut',
                    'required': 'required',
                }
            ),
            'direccion': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese su Direccion',
                    'required': 'required',
                }
            ),
            'telefono': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese su número telefónico',
                    'required': 'required',
                    'onkeypress':'return event.charCode >= 48 && event.charCode <= 57',
                }
            ),
        }

    def save(self, commit=True):  # Save the provided password in hashed format #
        user = super(UsuarioForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password"])

        if commit:
            user.save()
        return user


class UsuarioAddAdmForm(forms.ModelForm):
    class Meta:
        model = Usuario
        exclude = ['is_staff', 'is_superuser', 'last_login',
                   'date_joined', 'groups', 'user_permissions']
        labels = {'username': 'Nombre de usuario', 'first_name': 'Nombre', 'last_name': 'Apellidos',
                  'is_active': 'Habilitado', 'password': 'Contraseña', 'fk_tipo_usuario': 'Tipo Usuario',
                  'rut':'Rut'}
        help_texts = {'password': ' ', 'username': ' ', }

        widgets = {
            'direccion': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese direccion',
                    'required': 'required',
                }
            ),
            'password': forms.PasswordInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese contraseña',
                    'required': 'required',
                }
            ),
            'telefono': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese numero de telefono',
                    'required': 'required',
                    'onkeypress':'return event.charCode >= 48 && event.charCode <= 57',
                }
            ),
            'username': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese nombre de usuario',
                    'required': 'required',
                }
            ),
            'first_name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese nombre',
                    'required': 'required',
                }
            ),
            'last_name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese apellido',
                    'required': 'required',
                }
            ),
            'email': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese correo',
                    'required': 'required',
                }
            ),
            'rut': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese rut',
                    'required': 'required',
                }
            ),
            'fk_tipo_usuario': forms.Select(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese Tipo usuario',
                    'required': 'required',
                }
            ),
            
        }
    def save(self, commit=True):  # Save the provided password in hashed format #
        user = super(UsuarioForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password"])

        if commit:
            user.save()
        return user

class UsuarioAdmForm(forms.ModelForm):
    class Meta:
        model = Usuario
        exclude = ['is_staff', 'is_superuser', 'last_login',
                   'date_joined', 'groups', 'user_permissions', 'password']
        labels = {'username': 'Nombre de usuario', 'first_name': 'Nombre',
                  'last_name': 'Apellidos',  'is_active': 'Habilitado'}
        help_texts = {'password': ' ', 'username': ' ', }

        widgets = {
            'direccion': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese direccion',
                    'required': 'required',
                }
            ),
            'telefono': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese numero de telefono',
                    'required': 'required',
                }
            ),
            'username': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese nombre de usuario',
                    'required': 'required',
                }
            ),
            'first_name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese nombre',
                    'required': 'required',
                }
            ),
            'last_name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese apellido',
                    'required': 'required',
                }
            ),
            'email': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese correo',
                    'required': 'required',
                }
            ),
            'rut': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese rut',
                    'required': 'required',
                }
            ),
            'fk_tipo_usuario': forms.Select(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese Tipo usuario',
                    'required': 'required',
                }
            ),
            
        }


class UsuarioFormSu(forms.ModelForm):
    class Meta:
        model = Usuario
        exclude = []
        widgets = {
            'password': forms.PasswordInput(),
        }

# endregion

# region mantenedores


class ServicioExtraForm(forms.ModelForm):
    class Meta:
        model = ServicioExtra
        labels = {'nombre': 'Nombre', 'descripcion': 'Descripcion',
                  'costoDiario': 'Costo Diario'}
        exclude = []
        widgets = {
            'nombre': forms.TextInput(
                attrs={
                    'class': 'form-control',

turismo_real/AppWeb/templates/AppWeb/contratar_servicios.html
{% extends 'AppWeb/base.html' %}

{% load static %}

{% load humanize %}

{% block title %} Turismo Real {% endblock %}

{% block add_head %}

<style>
    .spad {
        padding-top: 0px;

    }
</style>

{% endblock %}

{% block section %}

<section class="page-title">
    <div class="page-title-img bg-img bg-overlay-darken"
        style="background-image: url({% static 'assets/img/pages/page-title-bg10.jpg' %});">
        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-lg-9 col-xl-8">
                    <div class="page-title-content py-7 py-md-8">
                        <div class="">
                            <h2 class="text-uppercase text-white font-weight-bold">Contratar Servicio</h2>
                        </div>
                        <p class="text-white mb-0">Aquí podrá contratar servicio de agendamiento o algun tour.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="pt-7 pb-9 pb-lg-10">
    <div class="container">
        <div class="row">
            <h1 class="element-title">Contratación Acercamiento</h1>
            <div class="col-md-12">
                <!--region  Transporte Acercamiento-->
                <div class="d-flex justify-content-between border-bottom mb-5 pb-5">
                
                    <div class="col-md-6">
                        <div class="row py-4">
                            <label class="control-label col-xl-7 text-center text-xl-right">¿Le gustaria acercamiento al
                                departamento?</label>
                            <div class="col-xl-5">
                                <div class="count-input mx-auto">
                                    <div class="custom-control custom-radio mb-1">
                                        <input id="transporte1" name="transporte" type="radio" class="custom-control-input"
                                            value="trans_si">
                                        <label class="custom-control-label radio-control-label" for="transporte1">
                                            Si
                                        </label>
                                    </div>

                                    <div class="custom-control custom-radio mb-1">
                                        <input id="transporte2" name="transporte" type="radio" class="custom-control-input"
                                            checked value="trans_no">
                                        <label class="custom-control-label radio-control-label" for="transporte2">
                                            No
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    
                    <div class="col-md-6">
                        <div class="Box py-4" style="display:none;">
                            <div class="form-group">
                                <label for="exampleInputText">Seleccione acercamiento</label>
                                <div class="select-default">
                                    <select class="select-option">
                                        <option>Seleccione opción</option>
                                        <option>Desde aeropuerto: $50.000</option>
                                        <option>Desde terminal de bus: $30.000</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                
                </div>
                <!--endregion  Transporte Acercamiento-->
            </div>
        </div>
        <div class="row">
            <h1 class="element-title">Contratación Tour</h1>
            <div class="col-md-12">
                <!--region  TOURS-->
                <div class="d-flex justify-content-between border-bottom mb-5 pb-5">
                    <div class="col-md-6">
                        <div class="row py-4">
                            <label class="control-label col-xl-7 text-center text-xl-right">¿Le gustaria hacer un
                                Tour?</label>
                            <div class="col-xl-5">
                                <div class="count-input mx-auto">
                                    <div class="custom-control custom-radio mb-1">
                                        <input id="tour1" name="tour" type="radio" class="custom-control-input"
                                            value="tour_si">
                                        <label class="custom-control-label radio-control-label" for="tour1">
                                            Si
                                        </label>
                                    </div>

                                    <div class="custom-control custom-radio mb-1">
                                        <input id="tour2" name="tour" type="radio" class="custom-control-input" checked
                                            value="tour_no">
                                        <label class="custom-control-label radio-control-label" for="tour2">
                                            No
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-md-6">
                        <div class="Box1 py-4" style="display:none;">
                            <div class="form-group mb-5">
                                <div class="row">
                                    <label for="inputTime"
                                        class="col-xl-4 col-form-label text-center text-xl-right px-2">Fecha
                                        Tour:</label>
                                    <div class="col-xl-8">
                                        <div class="form-group form-group-icon form-group-icon-category-2 mb-0">
                                            <i class="fa fa-calendar" aria-hidden="true"></i>
                                            <input type="text" class="form-control daterange-picker-category-2"
                                                name="dateRange" value="" placeholder="DD/MM/YYYY">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="exampleInputText">Seleccione Tour</label>
                                <div class="select-default">
                                    <select class="select-option">
                                        <option>Seleccione Tour</option>
                                        <option>Villarica: $50.000</option>
                                        <option>Pucon: $50.000</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                <!--Endregion  TOURS-->
            </div>
        </div>
        <div class="row">
            <div class="col-xl-12">
                <div class="mb-5">
                    <h1 class="element-title">Servicio Acercamiento Agendado</h1>
                    <p class="mb-6 line-height-28 h4">En la siguiente tabla podrá ver la signación de su acercamiento
                    </p>

                    <div class="row">
                        <div class="col-lg-12">

                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th scope="col">Tramo</th>
                                        <th scope="col">Precio</th>
                                        <th scope="col">Fecha Transporte</th>
                                        <th scope="col">Conductor</th>
                                        <th scope="col">Vehiculo</th>
                                        <th scope="col">Estado</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>Aeropuesto -> Depa</td>
                                        <td>$50.000</td>
                                        <td>10/12/2020</td>
                                        <td>Pedro Aguilar</td>
                                        <td>Hyundai H1 (PG-HJ-20)</td>
                                        <td>Asignado</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>


                    </div>
                </div>
            </div>

        </div>
        <div class="row">
            <div class="col-xl-12">
                <div class="mb-5">
                    <h1 class="element-title">TOURS Agendados</h1>
                    <p class="mb-6 line-height-28 h4">En la siguiente tabla podrá ver los tours agendados
                    </p>

                    <div class="row">
                        <div class="col-lg-12">

                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th scope="col">Imagen</th>
                                        <th scope="col">Tour(nombre)</th>
                                        <th scope="col">Duración</th>
                                        <th scope="col">Fecha</th>
                                        <th scope="col">Cantidad Personas</th>
                                        <th scope="col">Precio</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>imagen</td>
                                        <td>Pucón</td>
                                        <td>1 dia</td>
                                        <td>12/12/2020</td>
                                        <td>4 Personas</td>
                                        <td>$200.000</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>


                    </div>
                </div>
            </div>

        </div>
    </div>
</section>


{% endblock %}

{% block scripts %}

<script type="text/javascript">

    
    $(document).ready(function () {

        $('input[type="radio"]').click(function () {
            if ($(this).attr("value") == "trans_si") {
                $(".Box").show('slow');
            }
            if ($(this).attr("value") == "trans_no") {
                $(".Box").hide('slow');
            }
            if ($(this).attr("value") == "tour_si") {
                $(".Box1").show('slow');
            }
            if ($(this).attr("value") == "tour_no") {
                $(".Box1").hide('slow');

            }
        });

        $('input[type="radio"]').trigger('click');  // trigger the event

    });



</script>

{% endblock %}

turismo_real/AppWeb/templates/AppWeb/login.html
{% extends 'AppWeb/base.html' %}

{% block title %} Inicio Sesion {% endblock %}

{%block section %}


<p>{{ error_messages }}</p>

<section class="py-8 py-lg-10">
    <div class="container">
        <div class="text-center section-title">
            <h2 class="text-uppercase font-weight-bold position-relative">
                <span class="bg-white">
                    Iniciar Sesión
                </span>
            </h2>
            <p class="text-capitalize text-center">Ingresa con tu usuario para disfrutar nuestros servicios</p>
        </div>
        <br>
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <div class="mb-6 bg-white px-3 py-6 border-top border-top-5 border-primary rounded">
                    <h4 class="text-uppercase font-weight-bold">Ingrese sus datos</h4>
                    <form class="register-form" id="form_log">
                        {% csrf_token %}
                        <div class="form-group form-group-icon form-group-icon-dark mb-5">
                            {{ form.usr }}
                        </div>
                        <div class="form-group form-group-icon form-group-icon-dark mb-5">
                            {{ form.pwd }}
                        </div>
                        <div class="form-group form-button">
                            <button id="btn_log" class="btn btn-primary">Iniciar Sesión</button>
                            <!--<input id="btn_log"  class="btn btn-primary"  value="Iniciar Sesión"/>  -->
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-md-3"></div>
        </div>
    </div>
</section>


{% endblock %}

{% block scripts %}

<script type="text/javascript">


    $(document).ready(function () {

        $('#id_usr').on('paste', function (e) {
            e.preventDefault();
        });

        $('#id_usr').on('change', function (e) {
            var usr = e.target.value;
            validateUsername();
            validarFormulario();
        });

        $('#id_pwd').on('paste', function (e) {
            e.preventDefault();
        });

        $('#id_pwd').on('change', function (e) {
            var usr = e.target.value;
            validatePassword();
            validarFormulario();
        });

        function validarFormulario() {
            var username = $('#id_usr').val();
            if (validateUsername(username)) {
                var pass = $('#id_pwd').val();
                if (validatePassword(pass)) {
                    return true;
                }
            }

            return false;
        }


        //Add Login
        $("#btn_log").on("click", function (e) {
            if (validarFormulario()) {
                e.preventDefault();
                $.ajax({
                    type: "POST",
                    url: "/login",
                    data: $('#form_log').serialize(),
                    success: function (data) {
                        if (data.type == 'error') {
                            swal({
                                title: data.tittle,
                                text: data.mensaje,
                                type: data.type,
                                confirmButtonText: 'Aceptar'
                            })
                        } else {
                            swal({
                                title: data.tittle,
                                text: data.mensaje,
                                type: data.type,
                                confirmButtonText: 'Aceptar'
                            }, function (result) {
                                window.location.href = '/';
                            });
                        }
                    },
                    error: function (data) {
                        swal({
                            title: data.tittle,
                            text: data.mensaje,
                            type: data.type,
                            confirmButtonText: 'Aceptar'
                        })
                    }
                });
            }
        })
        //Fin Add Login

        ///Funcion para validar que el input username no este vacio
        function validateUsername(username) {

            if (username.length === 0) {
                $('#id_usr')[0].setCustomValidity("Debe ingresar Nombre usuario.")
                return false
            }
            else {
                $('#id_usr')[0].setCustomValidity("")

                return true
            }
        }

        /*Funcion para validar que el input password no este vacio 
        */
        function validatePassword(pass) {
            var decimal = /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[^a-zA-Z0-9])(?!.*\s).{8,15}$/;
            if(pass.length === 0){
                $('#id_pwd')[0].setCustomValidity("Debe ingresar una contraseña")
                return false
            }else {
                $('#id_pwd')[0].setCustomValidity("")
                return true
            }
            
            
        }

    });




</script>

{% endblock %}

turismo_real/AppWeb/templates/AppWeb/pago.html
{% extends 'AppWeb/base.html' %}

{% load static %}

{% block title %} Turismo Real {% endblock %}

{% block add_head %}

<style>
    .spad {
        padding-top: 0px;

    }
</style>

{% endblock %}

{% block section %}


<section class="aboutus-section spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="about-text">
                    <div class="section-title">
                        <h2>Agrega ocupante</h2>
                        <p class="f-para">Agregue ocupante de la reserva</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-12">
                <form id="form_add" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    {{form_payment_khipu.render}}
                    <div class="form-group">
                        <button id="btn_add" class="btn btn-dark">Agregar ocupante</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>


{% endblock %}

{% block scripts %}{% endblock %}