turismo_real/AppIntranet/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url
from AppIntranet.views import CreateDepartamentoView, EditDepaView, ListDepartamentoView
from AppIntranet.views import CreateServicioExtraView, EditServicioExtraView, ListServicioExtraView
from AppIntranet.views import listado_tours,servicios,otros_servicios,CreateServicioExtraView,EditServicioExtraView
from AppIntranet.views import CreateInventarioView, EditInventarioView, ListInventarioView
from AppIntranet.views import CreateUsuarioView, EditUsuarioView, ListUsuarioView
from AppIntranet.views import CreateDetalleInventarioView, EditDetalleInventarioView, ListDetalleInventarioView
from AppIntranet.views import CreateTipoEstado, TipoEstadoEditView, ListTipoEstadoView
from AppIntranet.views import CreateImagenDepartamentoView, EditImagenDepartamentoView, ListImagenDepartamentoView
from AppIntranet.views import CreateMantencionView, EditMantencionView, ListMantencionView
from AppIntranet.views import LoginAdmView, LogoutView

from AppIntranet.views import ReporteView, AgendaView, MantenedoresView, CheckinView
from AppIntranet.views import asignaciones_transporte,asignacion_conductor,asignacion_vehiculo
from AppIntranet.views import CheckOutView

urlpatterns = [
    
    path('index',views.index, name = "intranet"),

    url(r'^agenda$', AgendaView.as_view(), name='agenda'),
    url(r'^checkin$', CheckinView.as_view(), name='checkin'),
    url(r'^checkout$', CheckOutView.as_view(), name='check_out'),
    url(r'^mantenedores$', MantenedoresView.as_view(), name='mantenedores'),


    url(r'^reporte$', ReporteView.as_view(), name='reporte'),
    url(r'^estado/all$', ListTipoEstadoView.as_view(), name='list_estados'),
    url(r'^estado/new_estado$', CreateTipoEstado.as_view(), name='create_estado'),

    
    url(r'^departamento/add$', CreateDepartamentoView.as_view(), name='create_depa'),
    url(r'^departamento/edit/(?P<pk>[0-9]+)$', EditDepaView.as_view(), name='edit_depa'),
    url(r'^departamento/all$', ListDepartamentoView.as_view(), name='list_depa'),

    url(r'^otros_servicios/add$', CreateServicioExtraView.as_view(), name='create_serv'),
    url(r'^otros_servicios/edit/(?P<pk>[0-9]+)$', EditServicioExtraView.as_view(), name='edit_serv'),
    url(r'^otros_servicios/all$', ListServicioExtraView.as_view(), name='list_serv'),

    
    path('servicios/', views.servicios, name='list_serv_all'),
    path('otros_servicios/', views.otros_servicios, name='list_otros_serv'),

    path('aniadir_tour/', views.añadir_tour, name='add_tour'),
    path('editar_tour/', views.editar_tour, name='edit_tour'),
    path('tours_disponibles/', views.listado_tours, name='list_tours'),
    path('mantenedor_transporte/', views.transporte, name='list_transporte'),
    path('asignaciones_transporte/', views.asignaciones_transporte, name='asig_transporte'),
    path('asignacion_conductor/', views.asignacion_conductor, name='asig_conductor'),
    path('asignacion_vehiculo/', views.asignacion_vehiculo, name='asig_vehiculo'),

    url(r'^servicio/add$', CreateServicioExtraView.as_view(), name='create_serv'),
    url(r'^servicio/edit/(?P<pk>[0-9]+)$', EditServicioExtraView.as_view(), name='edit_serv'),
    url(r'^servicio/all$', ListServicioExtraView.as_view(), name='list_serv'),

    url(r'^inventario/add$', CreateInventarioView.as_view(), name='create_inv'),
    url(r'^inventario/edit/(?P<pk>[0-9]+)$', EditInventarioView.as_view(), name='edit_inv'),
    url(r'^inventario/all/(?P<pk>[0-9]+)$', ListInventarioView.as_view(), name='list_inv'),

    url(r'^usuario/add$', CreateUsuarioView.as_view(), name='create_usr'),
    url(r'^usuario/edit/(?P<pk>[0-9]+)$', EditUsuarioView.as_view(), name='edit_usr'),
    url(r'^usuario/all$', ListUsuarioView.as_view(), name='list_usr'),

    
    url(r'^tipoestado/add$', CreateTipoEstado.as_view(), name='create_tipoestado'),
    url(r'^tipoestado/edit/(?P<pk>[0-9]+)$', TipoEstadoEditView.as_view(), name='edit_tipoestado'),
    url(r'^tipoestado/all$', ListTipoEstadoView.as_view(), name='list_tipoestado'),

    url(r'^detalle/add$', CreateDetalleInventarioView.as_view(), name='create_deta'),
    url(r'^detalle/edit/(?P<pk>[0-9]+)$', EditDetalleInventarioView.as_view(), name='edit_deta'),
    url(r'^detalle/all/(?P<pk>[0-9]+)$', ListDetalleInventarioView.as_view(), name='list_deta'),

    url(r'^imagen/add$', CreateImagenDepartamentoView.as_view(), name='create_img'),
    url(r'^imagen/edit/(?P<pk>[0-9]+)$', EditImagenDepartamentoView.as_view(), name='edit_img'),
    url(r'^imagen/all/(?P<pk>[0-9]+)$', ListImagenDepartamentoView.as_view(), name='list_img'),

    url(r'^mantencion/add$', CreateMantencionView.as_view(), name='create_mant'),
    url(r'^mantencion/edit/(?P<pk>[0-9]+)$', EditMantencionView.as_view(), name='edit_mant'),
    url(r'^mantencion/all/(?P<pk>[0-9]+)$', ListMantencionView.as_view(), name='list_mant'),

    path('', LoginAdmView.as_view(), name='intranet_login'), 
    url(r'^logout$', LogoutView.as_view(), name='intranet_logout'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


turismo_real/AppWeb/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url

from AppWeb.views import Create as CreateUser, LoginView, LogoutView, ActivacionView #Usuario
from AppWeb.views import ListDepartamentosView, DetailDepartamentoView, SearchDepaView #Departamento
from AppWeb.views import ReservaView, CreateReservaView, MisReservasView #pruebas
from AppWeb.views import ListOcupanteView, CreateOcupanteView, EditOcupanteView, DeleteOcupanteView #Ocupantes
from AppWeb.views import TransporteView #Transporte
from AppWeb.views import PagoExitosoView, PagoErrorView #Pago
from AppWeb.views import ServicioAddView


urlpatterns = [
    
    path('',views.index, name = "index"),
    
    #region Ocupante
    url(r'^ocupantes/(?P<pk>[0-9]+)$', ListOcupanteView.as_view(), name='ocupantes'), 
    url(r'^ocupantes/add$', CreateOcupanteView.as_view(), name='create_ocu'), 
    url(r'^ocupantes/edit/(?P<pk>[0-9]+)$', EditOcupanteView.as_view(), name='edit_ocu'), 
    url(r'^ocupantes/del/(?P<pk>[0-9]+)$', DeleteOcupanteView.as_view(), name='del_ocu'), 
    #endregion Ocupante

    #region reserva
    url(r'^reserva$', ReservaView.as_view(), name='reserva'), 
    url(r'^mis_reservas$', MisReservasView.as_view(), name='mis_reservas'), 
    url(r'^reserva/add/(?P<pk>[0-9]+)$', CreateReservaView.as_view(), name='reserva_depto'), 
    url(r'^reserva/servicio/(?P<pk>[0-9]+)$', ServicioAddView.as_view(), name='cont_serv'), 
    #end reserva

    #region Departamento
    url(r'^departamentos$', ListDepartamentosView.as_view(), name='deptos_list'), #Cargar departamentos
    url(r'^busca/departamento$', SearchDepaView.as_view(), name='busca_depto'), #Cargar departamentos
    url(r'^departamento/(?P<pk>[0-9]+)$', DetailDepartamentoView.as_view(), name='detail_depto'), #Detalle del departamento(ID)

    #endregion Departamento
    
    #region usuario
    url(r'^new_user$', CreateUser.as_view(), name='create_user'), #Registrarse
    url(r'^login$', LoginView.as_view(), name='users_login'), #Iniciar sesion
    url(r'^logout$', LogoutView.as_view(), name='users_logout'), #Cerrar sesion
    url(r'^activation/(?P<pk>[0-9]+)$', ActivacionView.as_view(), name='activation'), #Activar usuario
    #endregion usuario

    #Region transporte
    url(r'^Transporte$', TransporteView.as_view(), name='Transporte'), #Muestra el transporte
    #endregion transporte

    #region Pagp
    url(r'^pago/exitoso$', PagoExitosoView.as_view(), name='PagoExito'),
    url(r'^pago/error$', PagoErrorView.as_view(), name='PagoError'),
    #endregion
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

turismo_real/turismo_real/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('AppWeb.urls')),
    path('intranet/',include('AppIntranet.urls')),
    url(r'^khipu/', include('khipu.urls')),

] 

turismo_real/AccesoDatos/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
#Blank false = required

# region Mantencion

class TipoUsuario(models.Model):
    nombre = models.CharField(max_length=50,blank=False)
    descripcion = models.CharField(max_length=500,blank=True)
    
    def __str__(self):
        return self.nombre


class Usuario(AbstractUser):
    fk_tipo_usuario = models.ForeignKey(TipoUsuario,null=True,blank=True,on_delete=models.CASCADE)

    rut = models.CharField(max_length=11,blank=False)
    #fecha_nac = models.DateField( blank=False)
    direccion = models.CharField(max_length=50,blank=False)
    telefono = models.CharField(max_length=12,blank=False)

    def _str_(self):
        return self.username

class ServicioExtra(models.Model):
    nombre = models.CharField(max_length=50,blank=False)
    descripcion = models.CharField(max_length=500,blank=False)
    costoDiario = models.IntegerField(blank=False)
    imagen = models.FileField(upload_to='documents/', blank=True)
    
    def __str__(self):
        return self.nombre

class Region(models.Model):
    nombre = models.CharField(max_length=50,blank=False)
    
    def __str__(self):
        return self.nombre

class Comuna(models.Model):
    fk_region = models.ForeignKey(Region,null=False,blank=False,on_delete=models.CASCADE)
    
    nombre = models.CharField(max_length=50,blank=False)
    
    def __str__(self):
        return self.nombre


class Departamento(models.Model):
    fk_comuna = models.ForeignKey(Comuna,null=True,blank=True,on_delete=models.CASCADE)
    
    direccion = models.CharField(max_length=50,blank=False)
    metros = models.IntegerField(blank=False)
    cantPersonas = models.IntegerField(blank=False)
    cantBanios = models.IntegerField(blank=False)
    cantDormitorios = models.IntegerField(blank=False)
    descripcion = models.CharField(max_length=500, blank=False)
    precioNoche = models.IntegerField(blank=False)

    estado = models.BooleanField(blank=True)
    dividendo = models.IntegerField(blank=False)
    contribuciones = models.IntegerField(blank=False)

    imagen = models.FileField(upload_to='documents/',blank=False)
    
    def __str__(self):
        return self.direccion

class Inventario(models.Model):
    fk_empleador = models.ForeignKey(Usuario,null=True,blank=True,on_delete=models.CASCADE)
    fk_departamento = models.ForeignKey(Departamento,null=False,blank=False,on_delete=models.CASCADE)

    nombre = models.CharField(max_length=50,blank=False)
    descripcion = models.CharField(max_length=500,blank=False)
    fechaRegistro = models.DateField( blank=False)
    
    def __str__(self):
        return self.nombre

class DetalleInventario(models.Model):
    fk_inventario = models.ForeignKey(Inventario,null=False,blank=False,on_delete=models.CASCADE)

    nombreObjeto = models.CharField(max_length=50,blank=False)
    cantidad = models.IntegerField(blank=False)
    descripcion = models.CharField(max_length=500,blank=True)
    costo = models.IntegerField(blank=False)
    
    def __str__(self):
        return self.nombreObjeto

class ImagenDepartamento(models.Model):
    fk_departamento = models.ForeignKey(Departamento,null=False,blank=False,on_delete=models.CASCADE)

    imagen = models.FileField(upload_to='documents/', blank=False)
    descripcion = models.CharField(max_length=500, blank=False)
    
    def __str__(self):
        return self.descripcion

class Mantencion(models.Model):
    fk_departamento = models.ForeignKey(Departamento,null=True,blank=True,on_delete=models.CASCADE)
    fk_empleado = models.ForeignKey(Usuario,null=True,blank=True,on_delete=models.CASCADE)

    nombre = models.CharField(max_length=50,blank=False)
    descripcion = models.CharField(max_length=500,blank=False)
    costo = models.IntegerField(blank=False)
    fechaRegistro = models.DateField( blank=True)
    fechaInicioProg = models.DateField( blank=False)
    fechaTerminoProg = models.DateField( blank=False)
    fechaRealInicio = models.DateField( blank=True, null=True)
    fechaRealTermino = models.DateField( blank=True, null=True)
    
    def __str__(self):
        return self.nombre

# endregion

# region Arriendo

class TipoEstado(models.Model):
    nombre = models.CharField(max_length=50,blank=False)
    descripcion = models.CharField(max_length=500,blank=True)
    
    def __str__(self):
        return self.nombre

class Arriendo(models.Model):
    fk_usuario = models.ForeignKey(Usuario,null=False,blank=False,on_delete=models.CASCADE)
    fk_tipo_estado = models.ForeignKey(TipoEstado,null=False,blank=False,on_delete=models.CASCADE)

    fechaRegistro = models.DateField( blank=False) 
    totalArriendo = models.IntegerField(blank=False)
    totalMulta = models.IntegerField(blank=True)
    totalServicio = models.IntegerField(blank=True)

    cantDias = models.IntegerField(blank=True)
    cantNinos = models.IntegerField(blank=True)
    cantAdultos = models.IntegerField(blank=True)

    cantPersonas = models.IntegerField()

    def __str__(self):
        return self.totalArriendo

class Reserva(models.Model):

    fechaInicio = models.DateField( blank=True) 
    fechaTermino = models.DateField( blank=True)
    costo = models.IntegerField()

    def __str__(self):
        return self.costo

class CheckIn(models.Model):
    fk_usuario = models.ForeignKey(Usuario,null=True,blank=True,on_delete=models.CASCADE)

    fechaRegistro = models.DateField( blank=True) 
    abonoFinal = models.IntegerField()
    observacion = models.CharField(max_length=500,blank=True)
    
    def __str__(self):
        return self.abonoFinal

class DetalleCheckIn(models.Model):
    fk_check_in = models.ForeignKey(CheckIn,null=True,blank=True,on_delete=models.CASCADE)

    nombreObjeto = models.CharField(max_length=500,blank=True)
    cantRegistrada = models.IntegerField()
    observacion = models.CharField(max_length=500,blank=True)
    
    def __str__(self):
        return self.nombreObjeto

class CheckOut(models.Model):
    fk_usuario = models.ForeignKey(Usuario,null=True,blank=True,on_delete=models.CASCADE)

    fechaRegistro = models.DateField( blank=True) 
    costoMulta = models.IntegerField()
    observacion = models.CharField(max_length=500,blank=True)

    def __str__(self):
        return self.costoMulta

class DetalleCheckOut(models.Model):
    fk_check_out = models.ForeignKey(CheckOut,null=True,blank=True,on_delete=models.CASCADE)

    nombreObjeto = models.CharField(max_length=500,blank=True)
    cantRegistrada = models.IntegerField()
    observacion = models.CharField(max_length=500,blank=True)
    
    def __str__(self):
        return self.nombreObjeto

class Multa(models.Model):
    fk_check_out = models.ForeignKey(CheckOut,null=True,blank=True,on_delete=models.CASCADE)

    nombreObjeto = models.CharField(max_length=500,blank=True)
    cantFaltante = models.IntegerField()
    observacion = models.CharField(max_length=500,blank=True)
    
    def __str__(self):
        return self.nombreObjeto

class Ocupante(models.Model):
    fk_arriendo = models.ForeignKey(Arriendo,null=True,blank=True,on_delete=models.CASCADE)
    
    rut = models.CharField(max_length=11,blank=False)
    nombres = models.CharField(max_length=50,blank=False)
    apellidos = models.CharField(max_length=50,blank=False)
    edad = models.IntegerField(blank=False)

    def __str__(self):
        return self.rut

class DetalleArriendo(models.Model):
    fk_departamento = models.ForeignKey(Departamento,null=True,blank=True,on_delete=models.CASCADE)
    fk_servicio_extra = models.ForeignKey(ServicioExtra,null=True,blank=True,on_delete=models.CASCADE)
    fk_arriendo = models.ForeignKey(Arriendo,null=True,blank=True,on_delete=models.CASCADE)
    fk_reserva = models.ForeignKey(Reserva,null=True,blank=True,on_delete=models.CASCADE)
    fk_check_in = models.ForeignKey(CheckIn,null=True,blank=True,on_delete=models.CASCADE)
    fk_check_out = models.ForeignKey(CheckOut,null=True,blank=True,on_delete=models.CASCADE)

    

    def __str__(self):
        return self.fk_arriendo

# endregion

turismo_real/AppIntranet/models.py
from django.db import models

# Create your models here.

turismo_real/AppIntranet/templates/AppIntranet/detalle/add_detalle_inv.html
{% extends 'AppIntranet/base.html' %}

{% load crispy_forms_tags %}

{% load static %}

{% block title %} Mantenedor Departamento {% endblock %}

{% block add_head %}{% endblock %}

{% block section %}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Agregar Objeto a Inventario "{{inv.nombre}}" del Departamento "{{departamento.direccion}}"</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'intranet' %}">Inicio</a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'mantenedores' %}">Mantenedores</a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'list_depa' %}">Mantenedor Departamento</a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'list_inv'  pk=departamento.pk %}">Mantenedor Inventario</a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'list_deta'  pk=inv.pk %}">Mantenedor Detalle Inventario</a>
            </li>
            <li class="breadcrumb-item active">
                <strong>Agregar Objeto</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox ">
                <div class="ibox-title">
                    <h5>Agregar Objeto al Inventario "{{inv.nombre}}" del Departamento "{{departamento.direccion}}" </h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>

                    </div>
                </div>
                <div class="ibox-content">
                    <form id="form_add" >
                        {% csrf_token %}

                        <div class="form-group row">
                            <div class="col-sm-12">
                                <div class="row">
                                    <div class="col-md-4">
                                        {{ form.nombreObjeto|as_crispy_field }}
                                    </div>
                                    <div class="col-md-4">
                                        {{ form.cantidad|as_crispy_field }}
                                    </div>
                                    <div class="col-md-4">
                                        {{ form.descripcion|as_crispy_field }}
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="form-group row">
                            <div class="col-lg-4">
                                {{ form.costo|as_crispy_field }}
                            </div>                            
                        </div>
                        
                        <div class="form-group col-lg-12 text-center">
                            <button id="btn_add" class="btn btn-primary btn-block btn-primary"><i class="fa fa-upload"></i> Agregar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>
</div>

{% block scripts %}

{% include 'AppIntranet/detalle/detalle_inv.html' %}

{% endblock %}

{% endblock %}

turismo_real/AppIntranet/templates/AppIntranet/detalle/detalle_inv.html
<script type="text/javascript">

  //Add Detalle inventario
  $(document).ready(function () {
    $("#btn_add").on("click", function (e) {
      if (validarFormulario()) {
        e.preventDefault();
        $.ajax({
          type: "POST",
          url: "/intranet/detalle/add",
          data: $('#form_add').serialize(),
          success: function (data) {
            if (data.type == 'error') {
              swal({
                title: data.tittle,
                text: data.mensaje,
                type: data.type,
                confirmButtonText: 'Aceptar'
              })
            } else {
              swal({
                title: data.tittle,
                text: data.mensaje,
                type: data.type,
                confirmButtonText: 'Aceptar'
              }, function (result) {
                window.location.href = '/intranet/detalle/all/' + '{{inv.pk}}';
              });
            }
          },
          error: function (data) {
            swal({
              title: data.tittle,
              text: data.mensaje,
              type: data.type,
              confirmButtonText: 'Aceptar'
            })
          }
        });
      }
    })
    //Fin Add Detalle inventario

    //Edit Detalle inventario
    $("#btn_edit").on("click", function (e) {
      if (validarFormulario()) {
        e.preventDefault();
        $.ajax({
          type: "POST",
          url: "/intranet/detalle/edit/" + '{{id}}',
          data: $('#form_edit').serialize(),
          success: function (data) {
            if (data.type == 'error') {
              swal({
                title: data.tittle,
                text: data.mensaje,
                type: data.type,
                confirmButtonText: 'Aceptar'
              })
            } else {
              swal({
                title: data.tittle,
                text: data.mensaje,
                type: data.type,
                confirmButtonText: 'Aceptar'
              }, function (result) {
                window.location.href = '/intranet/detalle/all/' + '{{inv.pk}}';
              });
            }
          },
          error: function (data) {
            swal({
              title: data.tittle,
              text: data.mensaje,
              type: data.type,
              confirmButtonText: 'Aceptar'
            })
          }
        });
      }
    })
    //Fin Edit Detalle inventario

    $('#id_nombreObjeto').on('paste', function (e) {
      e.preventDefault();
    });

    $('#id_nombreObjeto').on('change', function (e) {
      var nombre = e.target.value;
      validateNombre(nombre);
      validarFormulario();
    });
    
    $('#id_cantidad').on('paste', function (e) {
      e.preventDefault();
    });

    $('#id_cantidad').on('change', function (e) {
      var cant = e.target.value;
      validateCantidad(cant);
      validarFormulario();
    });
    
    $('#id_descripcion').on('paste', function (e) {
      e.preventDefault();
    });

    $('#id_descripcion').on('change', function (e) {
      var descrip = e.target.value;
      validateDescripcion(descrip);
      validarFormulario();
    });
    
    $('#id_costo').on('paste', function (e) {
      e.preventDefault();
    });

    $('#id_costo').on('change', function (e) {
      var costo = e.target.value;
      validateCosto(costo);
      validarFormulario();
    });

    function validarFormulario() {
      var nombre = $('#id_nombreObjeto').val();
      if (validateNombre(nombre)) {
        var cantidad = $('#id_cantidad').val();
        if (validateCantidad(cantidad)) {
          var descrip = $('#id_descripcion').val();
          if (validateDescripcion(descrip)) {
            var costo = $('#id_costo').val();
            if (validateCosto(costo)) {              
              return true;
            }
          }
        }
      }
      return false;
    }

    ///Funcion para validar que el input nombreObjeto no este vacio 
    function validateNombre(nombre) {
      if (nombre.length === 0) {
        $('#id_nombreObjeto')[0].setCustomValidity("Debe ingresar Nombre Objeto.")
        return false
      } else {
        $('#id_nombreObjeto')[0].setCustomValidity("")
        return true
      }
    }

    ///Funcion para validar que el input cantidad no este vacio 
    function validateCantidad(cant) {
      if (cant.length === 0) {
        $('#id_cantidad')[0].setCustomValidity("Debe ingresar Cantidad de Objetos.")
        return false
      } else {
        $('#id_cantidad')[0].setCustomValidity("")
        return true
      }
    }

    ///Funcion para validar que el input descripcion no este vacio 
    function validateDescripcion(descrip) {
      if (descrip.length === 0) {
        $('#id_descripcion')[0].setCustomValidity("Debe ingresar Descripción.")
        return false
      } else {
        $('#id_descripcion')[0].setCustomValidity("")
        return true
      }
    }

    ///Funcion para validar que el input costo no este vacio 
    function validateCosto(costo) {
      if (costo.length === 0) {
        $('#id_costo')[0].setCustomValidity("Debe ingresar Costo.")
        return false
      } else {
        $('#id_costo')[0].setCustomValidity("")
        return true
      }
    }

  });
</script>

turismo_real/AppIntranet/templates/AppIntranet/detalle/edit_detalle_inv.html
{% extends 'AppIntranet/base.html' %}

{% load crispy_forms_tags %}

{% load static %}

{% block title %} Mantenedor Departamento {% endblock %}

{% block add_head %}{% endblock %}

{% block section %}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Editar Objeto a Inventario "{{inv.nombre}}" del Departamento "{{departamento.direccion}}"</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'intranet' %}">Inicio</a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'mantenedores' %}">Mantenedores</a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'list_depa' %}">Mantenedor Departamento</a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'list_inv'  pk=departamento.pk %}">Mantenedor Inventario</a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'list_deta'  pk=inv.pk %}">Mantenedor Detalle Inventario</a>
            </li>
            <li class="breadcrumb-item active">
                <strong>Editar Objeto</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox ">
                <div class="ibox-title">
                    <h5>Editar Objeto "{{detalle.nombreObjeto}}" </h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>

                    </div>
                </div>
                <div class="ibox-content">
                    <form id="form_edit" >
                        {% csrf_token %}

                        <div class="form-group row">
                            <div class="col-sm-12">
                                <div class="row">
                                    <div class="col-md-4">
                                        {{ form.nombreObjeto|as_crispy_field }}
                                    </div>
                                    <div class="col-md-4">
                                        {{ form.cantidad|as_crispy_field }}
                                    </div>
                                    <div class="col-md-4">
                                        {{ form.descripcion|as_crispy_field }}
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="form-group row">
                            <div class="col-lg-4">
                                {{ form.costo|as_crispy_field }}
                            </div>                            
                        </div>
                        
                        <div class="form-group col-lg-12 text-center">
                            <button id="btn_edit" class="btn btn-primary btn-block btn-primary"><i class="fa fa-edit"></i> Editar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>
</div>

{% block scripts %}

{% include 'AppIntranet/detalle/detalle_inv.html' %}

{% endblock %}

{% endblock %}